version: '3.9'
services:
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: synthetic_data
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/synthetic_data
      NODE_ENV: development
      USE_AI: 'true'
      GEMINI_API_KEY: ${GEMINI_API_KEY:-change_me}
      GOOGLE_GENAI_MODEL: gemini-2.0-flash-001
      MODEL_TEMPERATURE: 0.25
      MAX_ROWS_PER_TABLE: 5000
      DEFAULT_NUM_RECORDS: 100
    ports:
      - '4000:4000'
    command: ['node', 'src/index.js']
    volumes:
      - .:/app
volumes:
  pgdata:
